language: go
os: linux
arch:
  - amd64
  - arm64
go:
  - "1.14"
sudo: required
services:
  - docker

go_import_path: github.com/GoogleContainerTools/container-diff

script:
 - travis_wait make test integration
